### ISSUE TITLE
Issue when starting with rendering app/pages/[...slug].vue

### ISSUE THREAD

**Issue by paul908** [nuxt-ui-pro/docs#82]
This app doesn't start, issue on Linux with npm run dev:

 ERROR  [nitro] [unhandledRejection] Cannot read properties of undefined (reading 'toc')

  at _sfc_ssrRender (app/pages/[...slug].vue:179:17)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:710:9)
  at node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:652:25

 ERROR  [nuxt] [request error] [fatal] [404] Page not found
  at Module.createError (./node_modules/h3/dist/index.mjs:78:15)  
  at Module.createError (./node_modules/nuxt/dist/app/composables/error.js:43:43)  
  at setup (./app/pages/[...slug].vue:70:36)

 ERROR  (node:322002) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1271)
(Use node --trace-warnings ... to show where the warning was created)

environment:
Node.js v20.11.1
Nuxt 3.12.4 with Nitro 2.9.7 

installed with: npx nuxi init -t github:nuxt-ui-pro/docs 
on 21/08/2024.

**Comment by paul908** [comment]
Second run, no issue anymore.
